import type { Metadata } from "next";
import { poppins } from "./fonts";
import "@nozna/ui/globals.css";

export const metadata: Metadata = {
  title: "Website - Nozna",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
